---
- name: Check if EPEL is installed
  stat:
    path: /etc/yum.repos.d/epel.repo
  register: st
  when: ansible_distribution == "RedHat"

- name: Download EPEL RPM
  get_url:
    url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    dest: "/tmp/epel{{ ansible_distribution_major_version }}.rpm"
    mode: 0440
  when: not st.stat.exists and ansible_distribution == "RedHat"

- name: Install EPEL repo
  yum:
    name: "/tmp/epel{{ ansible_distribution_major_version }}.rpm"
    state: present
  when: not st.stat.exists and ansible_distribution == "RedHat"
